In [2]:
import numpy as np
import pandas as pd

float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [4]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [7]:
string_data = pd.Series(['aardvark', None, np.nan, 'avocado'])
string_data

0    aardvark
1        None
2         NaN
3     avocado
dtype: object

In [8]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [9]:
float_data = pd.Series([1, 2, None], dtype='float64')
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [10]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [11]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [12]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [13]:
data[~data.isna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [16]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [17]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [18]:
data[4] = np.nan
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [19]:
data.dropna(how='all', axis=1)

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [20]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

0         1         2
0  1.211145       NaN       NaN
1 -0.323947       NaN       NaN
2 -2.486665       NaN -0.984665
3  0.639233       NaN -0.628099
4 -2.624764 -0.092919 -0.518360
5 -0.398499 -0.751268 -0.113937
6 -3.080345  0.612733 -1.649895

In [21]:
df.dropna()

0         1         2
4 -2.624764 -0.092919 -0.518360
5 -0.398499 -0.751268 -0.113937
6 -3.080345  0.612733 -1.649895

In [22]:
df.dropna(thresh=2)

0         1         2
2 -2.486665       NaN -0.984665
3  0.639233       NaN -0.628099
4 -2.624764 -0.092919 -0.518360
5 -0.398499 -0.751268 -0.113937
6 -3.080345  0.612733 -1.649895

In [26]:
df.dropna(axis=1, thresh=2)

0         1         2
0  1.211145       NaN       NaN
1 -0.323947       NaN       NaN
2 -2.486665       NaN -0.984665
3  0.639233       NaN -0.628099
4 -2.624764 -0.092919 -0.518360
5 -0.398499 -0.751268 -0.113937
6 -3.080345  0.612733 -1.649895

In [27]:
df.fillna(0)

0         1         2
0  1.211145  0.000000  0.000000
1 -0.323947  0.000000  0.000000
2 -2.486665  0.000000 -0.984665
3  0.639233  0.000000 -0.628099
4 -2.624764 -0.092919 -0.518360
5 -0.398499 -0.751268 -0.113937
6 -3.080345  0.612733 -1.649895

In [28]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  1.211145  0.500000  0.000000
1 -0.323947  0.500000  0.000000
2 -2.486665  0.500000 -0.984665
3  0.639233  0.500000 -0.628099
4 -2.624764 -0.092919 -0.518360
5 -0.398499 -0.751268 -0.113937
6 -3.080345  0.612733 -1.649895

In [30]:
df.T.fillna({1: 0.5, 2: -1}).T

0         1         2
0  1.211145       NaN       NaN
1 -0.323947  0.500000  0.500000
2 -2.486665 -1.000000 -0.984665
3  0.639233       NaN -0.628099
4 -2.624764 -0.092919 -0.518360
5 -0.398499 -0.751268 -0.113937
6 -3.080345  0.612733 -1.649895

In [31]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

0         1         2
0  0.377233 -0.830934 -0.632976
1 -0.271069  0.089964  0.499544
2  0.448395       NaN -0.028533
3  0.610170       NaN  0.738416
4 -0.620739       NaN       NaN
5 -1.095035       NaN       NaN

In [34]:
df.ffill()

0         1         2
0  0.377233 -0.830934 -0.632976
1 -0.271069  0.089964  0.499544
2  0.448395  0.089964 -0.028533
3  0.610170  0.089964  0.738416
4 -0.620739  0.089964  0.738416
5 -1.095035  0.089964  0.738416

In [35]:
df.ffill(limit=2)

0         1         2
0  0.377233 -0.830934 -0.632976
1 -0.271069  0.089964  0.499544
2  0.448395  0.089964 -0.028533
3  0.610170  0.089964  0.738416
4 -0.620739       NaN  0.738416
5 -1.095035       NaN  0.738416

In [36]:
df.fillna(0, limit=2)

0         1         2
0  0.377233 -0.830934 -0.632976
1 -0.271069  0.089964  0.499544
2  0.448395  0.000000 -0.028533
3  0.610170  0.000000  0.738416
4 -0.620739       NaN  0.000000
5 -1.095035       NaN  0.000000

In [37]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7, np.nan, 2., np.nan])
data.fillna(data.mean())

0    1.000
1    3.375
2    3.500
3    3.375
4    7.000
5    3.375
6    2.000
7    3.375
dtype: float64

In [38]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [39]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [40]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [41]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [42]:
data.drop_duplicates(subset=['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [43]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [44]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [45]:
data = pd.DataFrame({'food':['bacon', 'pulled pork', 'bacon',
                             'Pastrami', 'corned beef', 'Bacon',
                            'pastrami', 'honey ham', 'nova lox'],
                     'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [46]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [47]:
def get_animal(food):
    return meat_to_animal[food.lower()]

In [48]:
data['food'].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [49]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [50]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [51]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [52]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [53]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [55]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [56]:
def transform(x):
    return x[:4].upper()

data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [58]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [59]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [61]:
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [62]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [63]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [64]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [65]:
cats.categories[0]

Interval(18, 25, closed='right')

In [67]:
cats.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [68]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
cats = pd.cut(ages, bins, labels=group_names)

In [69]:
cats

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [70]:
data = np.random.uniform(size=20)
data

array([0.05112687, 0.27923091, 0.31112998, 0.99776074, 0.89504983,
       0.05693176, 0.35215814, 0.32787691, 0.36713237, 0.92554826,
       0.74819034, 0.03278674, 0.77807391, 0.67170569, 0.04186306,
       0.80165961, 0.00921363, 0.25524623, 0.63127531, 0.02020519])

In [72]:
cats = pd.cut(data, 4, precision=2)
cats

[(0.0082, 0.26], (0.26, 0.5], (0.26, 0.5], (0.75, 1.0], (0.75, 1.0], ..., (0.75, 1.0], (0.0082, 0.26], (0.0082, 0.26], (0.5, 0.75], (0.0082, 0.26]]
Length: 20
Categories (4, interval[float64, right]): [(0.0082, 0.26] < (0.26, 0.5] < (0.5, 0.75] < (0.75, 1.0]]

In [73]:
cats.value_counts()

(0.0082, 0.26]    7
(0.26, 0.5]       5
(0.5, 0.75]       3
(0.75, 1.0]       5
Name: count, dtype: int64

In [74]:
data = np.random.standard_normal(1000)
data

array([ 1.03707380e-01, -4.76834012e-01, -1.30819522e-02,  1.10333083e+00,
       -6.93178803e-01, -3.77312108e-01, -7.98051787e-01,  1.37937255e+00,
       -1.41789649e+00,  2.96680720e-01, -8.51070108e-01,  4.04732549e-01,
       -1.73484650e-01, -6.81750337e-01,  1.24845585e+00, -2.45043014e-01,
       -5.15957772e-01,  7.64150359e-01, -5.44582467e-01, -8.72519326e-01,
       -2.52249291e-01, -9.97857829e-01,  1.88904142e+00,  1.10093521e+00,
        7.54069105e-01,  1.86312254e-01, -8.02899190e-01, -1.27634772e+00,
        3.20059912e-01, -8.93898442e-01,  4.47053008e-01, -9.65652613e-02,
       -1.31136847e+00, -1.99633662e-01, -1.17001985e+00,  6.23050812e-01,
        1.34415482e+00,  9.94498236e-01, -8.99650553e-02,  3.14361287e+00,
       -1.22624511e+00,  1.84680151e+00, -1.91898100e+00, -4.40309430e-01,
       -2.34032618e-01, -1.04530142e+00,  3.85736816e-01,  1.30222943e+00,
        1.03322999e+00,  1.64516921e+00, -8.64912528e-01,  8.72922122e-01,
        2.74791639e+00, -

In [75]:
quartiles = pd.qcut(data, 4, precision=2)
quartiles

[(0.05, 0.72], (-0.66, 0.05], (-0.66, 0.05], (0.72, 3.49], (-3.0799999999999996, -0.66], ..., (0.72, 3.49], (-0.66, 0.05], (-0.66, 0.05], (0.05, 0.72], (0.05, 0.72]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.0799999999999996, -0.66] < (-0.66, 0.05] < (0.05, 0.72] < (0.72, 3.49]]

In [76]:
quartiles.value_counts()

(-3.0799999999999996, -0.66]    250
(-0.66, 0.05]                   250
(0.05, 0.72]                    250
(0.72, 3.49]                    250
Name: count, dtype: int64

In [78]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.018002     0.001901     0.105537    -0.004458
std       0.956695     1.031125     0.988945     0.997066
min      -2.992845    -3.057874    -2.959338    -2.963747
25%      -0.675499    -0.680858    -0.587106    -0.658160
50%      -0.001045     0.004384     0.130620    -0.028344
75%       0.605185     0.694016     0.801122     0.704848
max       3.062633     3.103614     2.777322     2.964015

In [80]:
col = data[2]
col[col.abs() > 2]

5      2.776285
23    -2.127670
26    -2.715874
47    -2.959338
53    -2.546197
130   -2.919926
214    2.638558
238    2.265706
302    2.777322
323   -2.147164
393    2.619644
397   -2.477309
421    2.141348
451    2.027972
458   -2.406016
496    2.590890
502   -2.467304
507    2.091968
519   -2.463941
539    2.276271
598   -2.620878
603   -2.127647
624    2.053629
626   -2.285906
629    2.732485
638    2.306801
660    2.027460
667    2.365350
676    2.603348
680    2.206412
705   -2.321040
720    2.768601
773    2.011263
793    2.158277
796    2.195068
806   -2.451915
824   -2.565447
831   -2.201393
857    2.113103
882   -2.043471
919   -2.019229
925    2.162056
941    2.629455
Name: 2, dtype: float64

In [83]:
data[(data.abs() > 3).any(axis=1)]

0         1         2         3
400  3.062633  0.036303 -1.572405  1.104672
422  0.323433  3.103614  1.025505  0.012309
893  0.453857  3.024699 -0.543959 -0.381890
988  0.652320 -3.057874 -0.939880  0.267999

In [87]:
data[data.abs() > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.018065     0.001830     0.105537    -0.004458
std       0.956495     1.030576     0.988945     0.997066
min      -2.992845    -3.000000    -2.959338    -2.963747
25%      -0.675499    -0.680858    -0.587106    -0.658160
50%      -0.001045     0.004384     0.130620    -0.028344
75%       0.605185     0.694016     0.801122     0.704848
max       3.000000     3.000000     2.777322     2.964015

In [88]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0 -1.0 -1.0
1 -1.0  1.0  1.0  1.0
2 -1.0  1.0  1.0 -1.0
3  1.0  1.0  1.0  1.0
4  1.0 -1.0 -1.0 -1.0

In [89]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [90]:
sampler = np.random.permutation(5)
sampler

array([2, 1, 3, 4, 0], dtype=int32)

In [91]:
df.take(sampler)

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6

In [92]:
df.iloc[sampler]

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6

In [93]:
col_sampler = np.random.permutation(df.columns)
col_sampler

array([4, 2, 6, 0, 3, 1, 5])

In [94]:
df.take(col_sampler, axis=1)

4   2   6   0   3   1   5
0   4   2   6   0   3   1   5
1  11   9  13   7  10   8  12
2  18  16  20  14  17  15  19
3  25  23  27  21  24  22  26
4  32  30  34  28  31  29  33

In [95]:
df.T.iloc[col_sampler].T

4   2   6   0   3   1   5
0   4   2   6   0   3   1   5
1  11   9  13   7  10   8  12
2  18  16  20  14  17  15  19
3  25  23  27  21  24  22  26
4  32  30  34  28  31  29  33

In [96]:
df.sample(3)

0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27

In [98]:
df.sample(frac=0.5)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6

In [99]:
df.sample(10, replace=True)

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
2  14  15  16  17  18  19  20

In [100]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [101]:
pd.get_dummies(df['key'])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [102]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummies = df[['data1']].join(dummies)
df_with_dummies

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [103]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('datasets/movielens/movies.dat', sep='::',
                       header=None, names=mnames, engine='python')
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [104]:
dummies = movies['genres'].str.get_dummies('|')
dummies

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
0          0          0          1           1       1      0            0   
1          0          1          0           1       0      0            0   
2          0          0          0           0       1      0            0   
3          0          0          0           0       1      0            0   
4          0          0          0           0       1      0            0   
...      ...        ...        ...         ...     ...    ...          ...   
3878       0          0          0           0       1      0            0   
3879       0          0          0           0       0      0            0   
3880       0          0          0           0       0      0            0   
3881       0          0          0           0       0      0            0   
3882       0          0          0           0       0      0            0   

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
0         0        0          0       0        0        0        0       0   
1         0        1          0       0        0        0        0       0   
2         0        0          0       0        0        0        1       0   
3         1        0          0       0        0        0        0       0   
4         0        0          0       0        0        0        0       0   
...     ...      ...        ...     ...      ...      ...      ...     ...   
3878      0        0          0       0        0        0        0       0   
3879      1        0          0       0        0        0        0       0   
3880      1        0          0       0        0        0        0       0   
3881      1        0          0       0        0        0        0       0   
3882      1        0          0       0        0        0        0       0   

      Thriller  War  Western  
0            0    0        0  
1            0    0        0  
2            0    0        0  
3            0    0        0  
4            0    0        0  
...        ...  ...      ...  
3878         0    0        0  
3879         0    0        0  
3880         0    0        0  
3881         0    0        0  
3882         1    0        0  

[3883 rows x 18 columns]

In [105]:
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [106]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [109]:
np.random.seed(12345)
values = np.random.uniform(size=10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [110]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [111]:
s = pd.Series([1, 2, 3, None])
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [112]:
s.dtype

dtype('float64')

In [113]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [114]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [115]:
s.dtype

Int64Dtype()

In [116]:
s[3]

<NA>

In [117]:
s[3] is pd.NA

True

In [118]:
s = pd.Series([1, 2, 3, None], dtype='Int64')
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [119]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [120]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [121]:
df = pd.DataFrame({'A': [1, 2, None, 4],
                   'B': ['one', 'two', None, 'three'],
                   'C': [False, None, True, False]})
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN   None   True
3  4.0  three  False

In [122]:
df['A'] = df['A'].astype('Int64')
df['B'] = df['B'].astype('string')
df['C'] = df['C'].astype('boolean')
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>   <NA>   True
3     4  three  False

In [123]:
val = 'a,b,  guido'
val.split(',')

['a', 'b', '  guido']

In [124]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [126]:
first, second, third = pieces
first + '::' + second + '::' + third

'a::b::guido'

In [127]:
'::'.join(pieces)

'a::b::guido'

In [128]:
'guido' in val

True

In [129]:
val.index(',')

1

In [130]:
val.find(':')

-1

In [132]:
val.count(',')

2

In [133]:
val.replace(',', '::')

'a::b::  guido'

In [134]:
val.replace(',', '')

'ab  guido'