In [1]:
import numpy as np
import pandas as pd

float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [2]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

In [3]:
string_data = pd.Series(['aardvark', None, np.nan, 'avocado'])
string_data

0    aardvark
1        None
2         NaN
3     avocado
dtype: object

In [4]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [5]:
float_data = pd.Series([1, 2, None], dtype='float64')
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [6]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

In [7]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [8]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [9]:
data[~data.isna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [10]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [11]:
data.dropna()

0    1    2
0  1.0  6.5  3.0

In [12]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [13]:
data[4] = np.nan
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [14]:
data.dropna(how='all', axis=1)

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [15]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan
df

0         1         2
0  0.337014       NaN       NaN
1  0.456283       NaN       NaN
2  0.089954       NaN  0.562964
3  1.263932       NaN -1.323375
4 -1.527274  0.375780  0.925130
5 -0.903940 -0.517164 -1.106900
6  1.296798 -0.560383 -0.420214

In [16]:
df.dropna()

0         1         2
4 -1.527274  0.375780  0.925130
5 -0.903940 -0.517164 -1.106900
6  1.296798 -0.560383 -0.420214

In [17]:
df.dropna(thresh=2)

0         1         2
2  0.089954       NaN  0.562964
3  1.263932       NaN -1.323375
4 -1.527274  0.375780  0.925130
5 -0.903940 -0.517164 -1.106900
6  1.296798 -0.560383 -0.420214

In [18]:
df.dropna(axis=1, thresh=2)

0         1         2
0  0.337014       NaN       NaN
1  0.456283       NaN       NaN
2  0.089954       NaN  0.562964
3  1.263932       NaN -1.323375
4 -1.527274  0.375780  0.925130
5 -0.903940 -0.517164 -1.106900
6  1.296798 -0.560383 -0.420214

In [19]:
df.fillna(0)

0         1         2
0  0.337014  0.000000  0.000000
1  0.456283  0.000000  0.000000
2  0.089954  0.000000  0.562964
3  1.263932  0.000000 -1.323375
4 -1.527274  0.375780  0.925130
5 -0.903940 -0.517164 -1.106900
6  1.296798 -0.560383 -0.420214

In [20]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0  0.337014  0.500000  0.000000
1  0.456283  0.500000  0.000000
2  0.089954  0.500000  0.562964
3  1.263932  0.500000 -1.323375
4 -1.527274  0.375780  0.925130
5 -0.903940 -0.517164 -1.106900
6  1.296798 -0.560383 -0.420214

In [21]:
df.T.fillna({1: 0.5, 2: -1}).T

0         1         2
0  0.337014       NaN       NaN
1  0.456283  0.500000  0.500000
2  0.089954 -1.000000  0.562964
3  1.263932       NaN -1.323375
4 -1.527274  0.375780  0.925130
5 -0.903940 -0.517164 -1.106900
6  1.296798 -0.560383 -0.420214

In [22]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

0         1         2
0  1.131460 -0.412512  0.712461
1  1.239009  2.043028 -1.083702
2 -1.018988       NaN  1.451454
3 -1.530693       NaN  1.081228
4  1.715593       NaN       NaN
5  0.868479       NaN       NaN

In [23]:
df.ffill()

0         1         2
0  1.131460 -0.412512  0.712461
1  1.239009  2.043028 -1.083702
2 -1.018988  2.043028  1.451454
3 -1.530693  2.043028  1.081228
4  1.715593  2.043028  1.081228
5  0.868479  2.043028  1.081228

In [24]:
df.ffill(limit=2)

0         1         2
0  1.131460 -0.412512  0.712461
1  1.239009  2.043028 -1.083702
2 -1.018988  2.043028  1.451454
3 -1.530693  2.043028  1.081228
4  1.715593       NaN  1.081228
5  0.868479       NaN  1.081228

In [25]:
df.fillna(0, limit=2)

0         1         2
0  1.131460 -0.412512  0.712461
1  1.239009  2.043028 -1.083702
2 -1.018988  0.000000  1.451454
3 -1.530693  0.000000  1.081228
4  1.715593       NaN  0.000000
5  0.868479       NaN  0.000000

In [26]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7, np.nan, 2., np.nan])
data.fillna(data.mean())

0    1.000
1    3.375
2    3.500
3    3.375
4    7.000
5    3.375
6    2.000
7    3.375
dtype: float64

In [27]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [28]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [29]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [30]:
data['v1'] = range(7)
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [31]:
data.drop_duplicates(subset=['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [32]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [33]:
data.drop_duplicates(['k1', 'k2'], keep='last')

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

In [34]:
data = pd.DataFrame({'food':['bacon', 'pulled pork', 'bacon',
                             'Pastrami', 'corned beef', 'Bacon',
                            'pastrami', 'honey ham', 'nova lox'],
                     'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [35]:
meat_to_animal = {
    'bacon': 'pig',
    'pulled pork': 'pig',
    'pastrami': 'cow',
    'corned beef': 'cow',
    'honey ham': 'pig',
    'nova lox': 'salmon'
}
data['animal'] = data['food'].map(str.lower).map(meat_to_animal)
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beef     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [36]:
def get_animal(food):
    return meat_to_animal[food.lower()]

In [37]:
data['food'].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [38]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [39]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [40]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [41]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [42]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [43]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [44]:
def transform(x):
    return x[:4].upper()

data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [45]:
data.index = data.index.map(transform)
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [46]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [47]:
data.rename(index={'OHIO': 'INDIANA'}, columns={'three': 'peekaboo'})

one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [48]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [49]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [50]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [51]:
cats.categories[0]

Interval(18, 25, closed='right')

In [52]:
cats.value_counts()

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [53]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
cats = pd.cut(ages, bins, labels=group_names)

In [54]:
cats

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [55]:
data = np.random.uniform(size=20)
data

array([0.06510583, 0.75993106, 0.99760785, 0.63193744, 0.63791307,
       0.90204878, 0.20789132, 0.50436527, 0.65402478, 0.41921024,
       0.33185047, 0.22357277, 0.71878796, 0.33001172, 0.79113953,
       0.91292361, 0.92736103, 0.34787945, 0.47173827, 0.48357667])

In [56]:
cats = pd.cut(data, 4, precision=2)
cats

[(0.064, 0.3], (0.53, 0.76], (0.76, 1.0], (0.53, 0.76], (0.53, 0.76], ..., (0.76, 1.0], (0.76, 1.0], (0.3, 0.53], (0.3, 0.53], (0.3, 0.53]]
Length: 20
Categories (4, interval[float64, right]): [(0.064, 0.3] < (0.3, 0.53] < (0.53, 0.76] < (0.76, 1.0]]

In [57]:
cats.value_counts()

(0.064, 0.3]    3
(0.3, 0.53]     7
(0.53, 0.76]    5
(0.76, 1.0]     5
Name: count, dtype: int64

In [58]:
data = np.random.standard_normal(1000)
data

array([-1.08568595e+00, -1.47261999e+00,  6.00058222e-01, -7.80501247e-02,
        6.54619211e-01, -4.24125519e-01, -1.96891416e-01,  5.24466139e-01,
        7.20711200e-01,  4.67232586e-01, -8.93129761e-01, -1.64725944e+00,
       -3.04534171e-01,  4.98707620e-01,  8.90882458e-01, -1.34759206e+00,
        4.40231579e-01,  6.11852025e-01,  3.87423654e-01, -6.88812392e-01,
        2.54540466e+00,  3.51198795e-01,  7.73770762e-01, -9.45491772e-01,
        1.49275684e+00, -9.50656350e-01,  7.21447018e-01, -5.74572913e-01,
        4.54278284e-01, -1.13299566e+00,  7.51002892e-01, -9.22527033e-01,
       -9.46891463e-01, -3.33152315e-01,  1.58181780e-02,  1.45979061e+00,
       -1.37980316e+00, -1.58530557e+00,  1.22357075e+00,  1.48169084e-01,
        2.47595625e+00, -1.38602988e-01,  5.62670608e-01, -8.23975978e-01,
       -3.74489008e-02,  8.32608969e-02, -2.29043169e-01, -1.50261214e+00,
        2.00490655e+00, -1.45132187e+00, -3.11246181e-02, -1.78357751e+00,
       -3.81881169e-01, -

In [59]:
quartiles = pd.qcut(data, 4, precision=2)
quartiles

[(-3.01, -0.62], (-3.01, -0.62], (0.033, 0.69], (-0.62, 0.033], (0.033, 0.69], ..., (-3.01, -0.62], (0.033, 0.69], (-0.62, 0.033], (-3.01, -0.62], (0.69, 4.0]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.01, -0.62] < (-0.62, 0.033] < (0.033, 0.69] < (0.69, 4.0]]

In [60]:
quartiles.value_counts()

(-3.01, -0.62]    250
(-0.62, 0.033]    250
(0.033, 0.69]     250
(0.69, 4.0]       250
Name: count, dtype: int64

In [61]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.005125    -0.036629     0.026665     0.001184
std       0.981843     0.972681     1.014562     1.020741
min      -3.071982    -2.690767    -3.408909    -2.875024
25%      -0.659621    -0.737606    -0.678967    -0.716048
50%       0.035632    -0.019261     0.009747    -0.002826
75%       0.667435     0.593591     0.727788     0.698836
max       2.986756     3.219758     3.621621     4.233914

In [62]:
col = data[2]
col[col.abs() > 2]

15    -2.569324
25     2.158025
35    -2.170115
77     2.455078
136    2.302020
159    2.150545
183   -3.408909
220   -2.363258
229    2.057769
276    2.313740
278   -2.474499
282   -2.170210
329    2.161696
343    2.041034
390    2.236167
395   -2.420268
398   -2.674859
411   -2.387443
418    2.539911
420   -2.152754
425   -2.248587
437    2.007099
453    2.233615
485    2.065223
504   -2.525923
550   -2.522235
588   -2.223782
598    2.146156
606    3.213984
639    2.295621
640   -2.121455
647    2.044354
668   -2.240611
674   -2.004485
702    2.397357
706    3.621621
709   -2.238843
745   -2.176290
760    2.148492
772    2.387200
779    2.003635
818   -2.003381
842    2.129474
898    2.024459
909    2.205053
911    2.102256
925   -2.016585
928    2.847887
986    2.673577
Name: 2, dtype: float64

In [63]:
data[(data.abs() > 3).any(axis=1)]

0         1         2         3
42  -0.656635 -0.668067 -0.381409  3.173925
97  -3.071982 -0.411122 -0.635261  1.700085
183  0.722632 -0.661332 -3.408909  1.394211
214 -1.493210  3.219758  1.212678 -1.376739
392  0.168001  0.349473 -1.170484  4.233914
502 -1.414188 -0.499444 -1.262036  3.684015
606  0.934937  0.517146  3.213984  0.762579
706 -0.195377  0.454702  3.621621 -0.477441

In [64]:
data[data.abs() > 3] = np.sign(data) * 3
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.005053    -0.036849     0.026239    -0.000908
std       0.981620     0.971970     1.010586     1.013571
min      -3.000000    -2.690767    -3.000000    -2.875024
25%      -0.659621    -0.737606    -0.678967    -0.716048
50%       0.035632    -0.019261     0.009747    -0.002826
75%       0.667435     0.593591     0.727788     0.698836
max       2.986756     3.000000     3.000000     3.000000

In [65]:
np.sign(data).head()

0    1    2    3
0 -1.0  1.0 -1.0  1.0
1 -1.0 -1.0 -1.0 -1.0
2 -1.0 -1.0  1.0 -1.0
3 -1.0 -1.0 -1.0 -1.0
4  1.0  1.0  1.0 -1.0

In [66]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))
df

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

In [67]:
sampler = np.random.permutation(5)
sampler

array([3, 1, 2, 4, 0], dtype=int32)

In [68]:
df.take(sampler)

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6

In [69]:
df.iloc[sampler]

0   1   2   3   4   5   6
3  21  22  23  24  25  26  27
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
0   0   1   2   3   4   5   6

In [70]:
col_sampler = np.random.permutation(df.columns)
col_sampler

array([3, 2, 5, 6, 1, 0, 4])

In [71]:
df.take(col_sampler, axis=1)

3   2   5   6   1   0   4
0   3   2   5   6   1   0   4
1  10   9  12  13   8   7  11
2  17  16  19  20  15  14  18
3  24  23  26  27  22  21  25
4  31  30  33  34  29  28  32

In [72]:
df.T.iloc[col_sampler].T

3   2   5   6   1   0   4
0   3   2   5   6   1   0   4
1  10   9  12  13   8   7  11
2  17  16  19  20  15  14  18
3  24  23  26  27  22  21  25
4  31  30  33  34  29  28  32

In [73]:
df.sample(3)

0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6

In [74]:
df.sample(frac=0.5)

0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
3  21  22  23  24  25  26  27

In [75]:
df.sample(10, replace=True)

0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13

In [76]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [77]:
pd.get_dummies(df['key'])

a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [78]:
dummies = pd.get_dummies(df['key'], prefix='key')
df_with_dummies = df[['data1']].join(dummies)
df_with_dummies

data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False

In [79]:
mnames = ['movie_id', 'title', 'genres']
movies = pd.read_table('datasets/movielens/movies.dat', sep='::',
                       header=None, names=mnames, engine='python')
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [80]:
dummies = movies['genres'].str.get_dummies('|')
dummies

Action  Adventure  Animation  Children's  Comedy  Crime  Documentary  \
0          0          0          1           1       1      0            0   
1          0          1          0           1       0      0            0   
2          0          0          0           0       1      0            0   
3          0          0          0           0       1      0            0   
4          0          0          0           0       1      0            0   
...      ...        ...        ...         ...     ...    ...          ...   
3878       0          0          0           0       1      0            0   
3879       0          0          0           0       0      0            0   
3880       0          0          0           0       0      0            0   
3881       0          0          0           0       0      0            0   
3882       0          0          0           0       0      0            0   

      Drama  Fantasy  Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  \
0         0        0          0       0        0        0        0       0   
1         0        1          0       0        0        0        0       0   
2         0        0          0       0        0        0        1       0   
3         1        0          0       0        0        0        0       0   
4         0        0          0       0        0        0        0       0   
...     ...      ...        ...     ...      ...      ...      ...     ...   
3878      0        0          0       0        0        0        0       0   
3879      1        0          0       0        0        0        0       0   
3880      1        0          0       0        0        0        0       0   
3881      1        0          0       0        0        0        0       0   
3882      1        0          0       0        0        0        0       0   

      Thriller  War  Western  
0            0    0        0  
1            0    0        0  
2            0    0        0  
3            0    0        0  
4            0    0        0  
...        ...  ...      ...  
3878         0    0        0  
3879         0    0        0  
3880         0    0        0  
3881         0    0        0  
3882         1    0        0  

[3883 rows x 18 columns]

In [81]:
dummies.iloc[:10, :6]

Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [82]:
movies_windic = movies.join(dummies.add_prefix('Genre_'))
movies_windic.iloc[0]

movie_id                                       1
title                           Toy Story (1995)
genres               Animation|Children's|Comedy
Genre_Action                                   0
Genre_Adventure                                0
Genre_Animation                                1
Genre_Children's                               1
Genre_Comedy                                   1
Genre_Crime                                    0
Genre_Documentary                              0
Genre_Drama                                    0
Genre_Fantasy                                  0
Genre_Film-Noir                                0
Genre_Horror                                   0
Genre_Musical                                  0
Genre_Mystery                                  0
Genre_Romance                                  0
Genre_Sci-Fi                                   0
Genre_Thriller                                 0
Genre_War                                      0
Genre_Western       

In [83]:
np.random.seed(12345)
values = np.random.uniform(size=10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [84]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

(0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

In [85]:
s = pd.Series([1, 2, 3, None])
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [86]:
s.dtype

dtype('float64')

In [87]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [88]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [89]:
s.dtype

Int64Dtype()

In [90]:
s[3]

<NA>

In [91]:
s[3] is pd.NA

True

In [92]:
s = pd.Series([1, 2, 3, None], dtype='Int64')
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [93]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())

In [94]:
s

0      one
1      two
2     <NA>
3    three
dtype: string

In [95]:
df = pd.DataFrame({'A': [1, 2, None, 4],
                   'B': ['one', 'two', None, 'three'],
                   'C': [False, None, True, False]})
df

A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN   None   True
3  4.0  three  False

In [96]:
df['A'] = df['A'].astype('Int64')
df['B'] = df['B'].astype('string')
df['C'] = df['C'].astype('boolean')
df

A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>   <NA>   True
3     4  three  False

In [97]:
val = 'a,b,  guido'
val.split(',')

['a', 'b', '  guido']

In [98]:
pieces = [x.strip() for x in val.split(',')]
pieces

['a', 'b', 'guido']

In [99]:
first, second, third = pieces
first + '::' + second + '::' + third

'a::b::guido'

In [100]:
'::'.join(pieces)

'a::b::guido'

In [101]:
'guido' in val

True

In [102]:
val.index(',')

1

In [103]:
val.find(':')

-1

In [104]:
val.count(',')

2

In [105]:
val.replace(',', '::')

'a::b::  guido'

In [106]:
val.replace(',', '')

'ab  guido'

In [107]:
import re

text = "foo    bar\t baz  \tqux"
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [108]:
regex = re.compile('\s+')
regex.split(text)

['foo', 'bar', 'baz', 'qux']

In [109]:
regex.findall(text)

['    ', '\t ', '  \t']

In [110]:
text = """Dave dave@google.com
Steve steve@gmail.com
Rob rob@gmail.com
Ryan ryan@yahoo.com"""

pattern = r'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}'
regex = re.compile(pattern, flags=re.IGNORECASE)

In [111]:
regex.findall(text)

['dave@google.com', 'steve@gmail.com', 'rob@gmail.com', 'ryan@yahoo.com']

In [112]:
m = regex.search(text)
m

<re.Match object; span=(5, 20), match='dave@google.com'>

In [113]:
text[m.start():m.end()]

'dave@google.com'

In [114]:
print(regex.match(text))

None


In [115]:
print(regex.sub('REDACTED', text))

Dave REDACTED
Steve REDACTED
Rob REDACTED
Ryan REDACTED


In [116]:
pattern = r'([A-Za-z0-9._%+-]+)@([A-Za-z0-9.-]+)\.([A-Za-z]{2,4})'
regex = re.compile(pattern, flags=re.IGNORECASE)

In [117]:
m = regex.match('wesm@bright.net')
m.groups()

('wesm', 'bright', 'net')

In [118]:
regex.findall(text)

[('dave', 'google', 'com'),
 ('steve', 'gmail', 'com'),
 ('rob', 'gmail', 'com'),
 ('ryan', 'yahoo', 'com')]

In [119]:
print(regex.sub(r'Username: \1, Domain: \2, Suffix: \3', text))

Dave Username: dave, Domain: google, Suffix: com
Steve Username: steve, Domain: gmail, Suffix: com
Rob Username: rob, Domain: gmail, Suffix: com
Ryan Username: ryan, Domain: yahoo, Suffix: com


In [120]:
data = {'Dave': 'dava@google.com', 'Steve': 'steve@gmail.com',
        'Rob': 'rob@gmail.com', 'Wes': np.nan}
data = pd.Series(data)
data

Dave     dava@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                  NaN
dtype: object

In [121]:
data.isna()

Dave     False
Steve    False
Rob      False
Wes       True
dtype: bool

In [122]:
data.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes        NaN
dtype: object

In [123]:
data_as_string_ext = data.astype('string')
data_as_string_ext

Dave     dava@google.com
Steve    steve@gmail.com
Rob        rob@gmail.com
Wes                 <NA>
dtype: string

In [124]:
data_as_string_ext.str.contains('gmail')

Dave     False
Steve     True
Rob       True
Wes       <NA>
dtype: boolean

In [125]:
pattern = r'([A-Za-z0-9._%+-]+)@([A-Za-z0-9.-]+)\.([A-Za-z]{2,4})'
data.str.findall(pattern)

Dave     [(dava, google, com)]
Steve    [(steve, gmail, com)]
Rob        [(rob, gmail, com)]
Wes                        NaN
dtype: object

In [126]:
matches = data.str.findall(pattern, flags=re.IGNORECASE).str[0]
matches

Dave     (dava, google, com)
Steve    (steve, gmail, com)
Rob        (rob, gmail, com)
Wes                      NaN
dtype: object

In [127]:
matches.str.get(1)

Dave     google
Steve     gmail
Rob       gmail
Wes         NaN
dtype: object

In [128]:
data.str[:5]

Dave     dava@
Steve    steve
Rob      rob@g
Wes        NaN
dtype: object

In [129]:
data.str.extract(pattern, flags=re.IGNORECASE)

0       1    2
Dave    dava  google  com
Steve  steve   gmail  com
Rob      rob   gmail  com
Wes      NaN     NaN  NaN

In [130]:
values = pd.Series(['Apple', 'Orange', 'Banana', 'Apple'] * 2)
values

0     Apple
1    Orange
2    Banana
3     Apple
4     Apple
5    Orange
6    Banana
7     Apple
dtype: object

In [131]:
values.unique()

array(['Apple', 'Orange', 'Banana'], dtype=object)

In [132]:
pd.unique(values)

array(['Apple', 'Orange', 'Banana'], dtype=object)

In [133]:
values.count()

np.int64(8)

In [134]:
pd.value_counts(values)

F:\Logs\Temp\ipykernel_24144\3297668723.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)


Apple     4
Orange    2
Banana    2
Name: count, dtype: int64

In [135]:
values.value_counts()

Apple     4
Orange    2
Banana    2
Name: count, dtype: int64

In [136]:
values = pd.Series([0, 1, 0, 0] *  2)
dim = pd.Series(['apple', 'orange'])
values

0    0
1    1
2    0
3    0
4    0
5    1
6    0
7    0
dtype: int64

In [137]:
dim

0     apple
1    orange
dtype: object

In [138]:
dim.take(values)

0     apple
1    orange
0     apple
0     apple
0     apple
1    orange
0     apple
0     apple
dtype: object

In [139]:
fruits = ['apple', 'orange', 'apple', 'apple'] * 2
N = len(fruits)
rng = np.random.default_rng(seed=12345)

In [140]:
df = pd.DataFrame({'fruit': fruits,
                   'basket_id': np.arange(N),
                   'count': rng.integers(3, 15, size=N),
                   'weight': rng.uniform(0, 4, size=N)},
                   columns=['basket_id', 'fruit', 'count', 'weight'])
df

basket_id   fruit  count    weight
0          0   apple     11  1.564438
1          1  orange      5  1.331256
2          2   apple     12  2.393235
3          3   apple      6  0.746937
4          4   apple      5  2.691024
5          5  orange     12  3.767211
6          6   apple     10  0.992983
7          7   apple     11  3.795525

In [141]:
fruit_cat = df['fruit'].astype('category')
fruit_cat

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [142]:
c = fruit_cat.array
type(c)

pandas.core.arrays.categorical.Categorical

In [143]:
c.categories

Index(['apple', 'orange'], dtype='object')

In [144]:
c.codes

array([0, 1, 0, 0, 0, 1, 0, 0], dtype=int8)

In [145]:
dict(enumerate(c.categories))

{0: 'apple', 1: 'orange'}

In [146]:
df['fruit'] = df['fruit'].astype('category')
df['fruit']

0     apple
1    orange
2     apple
3     apple
4     apple
5    orange
6     apple
7     apple
Name: fruit, dtype: category
Categories (2, object): ['apple', 'orange']

In [147]:
my_categories = pd.Categorical(['foo', 'bar', 'baz', 'foo', 'bar'])
my_categories

['foo', 'bar', 'baz', 'foo', 'bar']
Categories (3, object): ['bar', 'baz', 'foo']

In [148]:
categories = ['foo', 'bar', 'baz']
codes = [0, 1, 2, 0, 0, 1]
my_cat_2 = pd.Categorical.from_codes(codes, categories)
my_cat_2

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo', 'bar', 'baz']

In [149]:
ordered_cat = pd.Categorical.from_codes(codes, categories, ordered=True)
ordered_cat

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [150]:
my_cat_2.as_ordered()

['foo', 'bar', 'baz', 'foo', 'foo', 'bar']
Categories (3, object): ['foo' < 'bar' < 'baz']

In [151]:
draws = rng.standard_normal(1000)
draws[:5]

array([-0.75938718,  0.90219827, -0.46695317, -0.06068952,  0.78884434])

In [152]:
bins = pd.qcut(draws, 4, precision=2)
bins

[(-3.13, -0.67], (0.69, 3.21], (-0.67, 0.02], (-0.67, 0.02], (0.69, 3.21], ..., (0.69, 3.21], (0.02, 0.69], (0.02, 0.69], (0.69, 3.21], (0.69, 3.21]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.13, -0.67] < (-0.67, 0.02] < (0.02, 0.69] < (0.69, 3.21]]

In [153]:
bins = pd.qcut(draws, 4, precision=2, labels=['Q1', 'Q2', 'Q3', 'Q4'])
bins

['Q1', 'Q4', 'Q2', 'Q2', 'Q4', ..., 'Q4', 'Q3', 'Q3', 'Q4', 'Q4']
Length: 1000
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [154]:
bins.codes[:10]

array([0, 3, 1, 1, 3, 0, 2, 3, 3, 1], dtype=int8)

In [155]:
bins.categories[:10]

Index(['Q1', 'Q2', 'Q3', 'Q4'], dtype='object')

In [157]:
bins = pd.Series(bins, name='quartile')
results = (pd.Series(draws).groupby(bins, observed=False).agg(['count', 'min', 'max']).reset_index())
results

quartile  count       min       max
0       Q1    250 -3.119609 -0.673305
1       Q2    250 -0.672703  0.019655
2       Q3    250  0.019958  0.692732
3       Q4    250  0.695674  3.211418

In [158]:
results['quartile']

0    Q1
1    Q2
2    Q3
3    Q4
Name: quartile, dtype: category
Categories (4, object): ['Q1' < 'Q2' < 'Q3' < 'Q4']

In [159]:
N = 10_000_000
labels = pd.Series(['foo', 'bar', 'baz', 'qux'] * (N // 4))
categories = labels.astype('category')

In [160]:
labels.memory_usage(deep=True)

600000128

In [161]:
categories.memory_usage(deep=True)

10000540

In [163]:
%timeit labels.astype('category')

449 ms ± 55.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [166]:
%time _ = labels.astype('category')

CPU times: total: 469 ms
Wall time: 444 ms


In [167]:
%%time
_ = labels.astype('category')

CPU times: total: 484 ms
Wall time: 486 ms


In [168]:
%timeit labels.value_counts()

318 ms ± 6.92 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [169]:
%timeit categories.value_counts()

50.6 ms ± 8.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [170]:
s = pd.Series(['a', 'b', 'c', 'd'] * 2)
cat_s = s.astype('category')
cat_s

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [171]:
cat_s.cat.codes

0    0
1    1
2    2
3    3
4    0
5    1
6    2
7    3
dtype: int8

In [172]:
cat_s.cat.categories

Index(['a', 'b', 'c', 'd'], dtype='object')

In [173]:
actual_categories = ['a', 'b', 'c', 'd', 'e']
cat_s2 = cat_s.cat.set_categories(actual_categories)
cat_s2

0    a
1    b
2    c
3    d
4    a
5    b
6    c
7    d
dtype: category
Categories (5, object): ['a', 'b', 'c', 'd', 'e']

In [174]:
cat_s.value_counts()

a    2
b    2
c    2
d    2
Name: count, dtype: int64

In [175]:
cat_s2.value_counts()

a    2
b    2
c    2
d    2
e    0
Name: count, dtype: int64

In [176]:
cat_s3 = cat_s[cat_s.isin(['a', 'b'])]
cat_s3

0    a
1    b
4    a
5    b
dtype: category
Categories (4, object): ['a', 'b', 'c', 'd']

In [177]:
cat_s3.cat.remove_unused_categories()

0    a
1    b
4    a
5    b
dtype: category
Categories (2, object): ['a', 'b']

In [178]:
cat_s = pd.Series(['a', 'b', 'c', 'd'] * 2).astype('category')
pd.get_dummies(cat_s)

a      b      c      d
0   True  False  False  False
1  False   True  False  False
2  False  False   True  False
3  False  False  False   True
4   True  False  False  False
5  False   True  False  False
6  False  False   True  False
7  False  False  False   True