In [1]:
import torch

In [5]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [6]:
x.numel()

12

In [7]:
x.shape

torch.Size([12])

In [8]:
X = x.reshape(3, 4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
x[3]

tensor(3.)

In [10]:
X[0, 3]

tensor(3.)

In [11]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [13]:
torch.randn(3, 4)

tensor([[-0.1016, -0.1583, -0.5369,  0.4025],
        [-0.3550,  0.1017,  0.2228, -0.6653],
        [ 0.6254,  0.6299,  0.1230,  0.2785]])

In [14]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [15]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [16]:
X[1, 2]=17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [17]:
X[:2, :]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [18]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4668,  59874.1406])

In [19]:
x

tensor([12., 12., 12., 12., 12., 12., 12., 12.,  8.,  9., 10., 11.])

In [20]:
x = torch.tensor([1.1, 2.2, 3.3, 4.4])
y = torch.tensor([0, 110, 120, 119])
x+y, x-y, x*y, x/y

(tensor([  1.1000, 112.2000, 123.3000, 123.4000]),
 tensor([   1.1000, -107.8000, -116.7000, -114.6000]),
 tensor([  0.0000, 242.0000, 396.0000, 523.6000]),
 tensor([   inf, 0.0200, 0.0275, 0.0370]))

In [21]:
x**y

tensor([1.0000e+00, 4.6398e+37,        inf,        inf])

In [26]:
X = torch.arange(12, dtype=torch.float32).reshape([3, 4])
Y = torch.tensor([[2.0, 1, 3, 4], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  3.,  4.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  3.,  4.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [27]:
X == Y

tensor([[False,  True, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [28]:
X.sum()

tensor(66.)

In [29]:
X > Y

tensor([[False, False, False, False],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [30]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [31]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [32]:
before = id(Y)
Y = X + Y
id(Y) == before

False

In [33]:
before = id(Y)
Y[:] = X + Y
id(Y) == before

True

In [34]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 1867943650208
id(Z): 1867943650208


In [35]:
A = X.numpy()
B = torch.from_numpy(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)